# after_success：执行完测试后，发布到GitHub pages

sudo: false
language: node_js
node_js: 10
addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script:
  - npm run test
after_success:
  - sh build/release.sh

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master