# after_success：执行完测试后，发布到GitHub pages

sudo: false
language: node_js
node_js: 10
addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script:
  - npm run test
after_success:
  - sh build/release.sh

# 发布npm包
node_js: "8"
before_deploy: 
  - npm run clean
  - npm run lib
deploy:
  provider: npm
  email: "${NPM_EMAIL}"
  skip_cleanup: true
  api_key: "${NPM_TOKEN}"
  on:
    tags: true, # git tag 打标签才发包
    # branch: master # master分支push才发包
  tag: latest

# 指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

# 定义环境变量
env:
  - COMMIT_M="发布gh-page的文字描述"